### ISSUE TITLE
x_sigma=0.1@fitting_kura.py : 宣言するだけで使われてないと思うのですが...

### ISSUE THREAD

**Issue by kz-halfmoon** [furukawa-laboratory/somf#134]
**target code 対象となるコード** 
somf/tutorials/som/kura_data/fitting_kura.py

**Is your feature request related to a problem? Please describe. この機能追加リクエストは何かの問題に関連していますか？**
fitting_kura.pyの15行目の記述：`x_sigma = 0.1`
これは，宣言するだけで使われていないと思うのですが，理解はあっているでしょうか．
**Describe the solution you'd like 望む解決策の説明**
該当コード`x_sigma = 0.1`の削除

**Additional context 追加の説明**
宮崎さんに聞いたら，Issue立てといたほうがいい，とアドバイスしてくれたので立ててみました．

**Comment by ae14watanabe** [comment]
ほんとですね。これはウッカリですね。本当は26行目の`0.1` のところに`x_sigma`を入れたかったんだと思う。にしても `x_sigma` とか変数名だと意図が分かりにくいですね。
https://github.com/furukawa-laboratory/somf/blob/1abb81a3d85c674bd73d109ef3501b54684893ac/tutorials/som/kura_data/fitting_kura.py#L26

**Comment by kz-halfmoon** [comment]
なるほど，そこの0.1でしたか．
観測空間のノードに乗せるノイズですかね？
素人目ですが，近傍半径に関わる変数かなと思ってました．

**Comment by ae14watanabe** [comment]
@kz-halfmoon 
観測空間の **データ** に乗せるノイズですね。（ちなみに潜在空間にある代表点をノード、観測空間にあるノードの写像先を参照ベクトルと呼んでます。）
それがどれだけ大きいノイズにするのかをコントロールする変数ですね。

ノイズを乗せない場合は、滑らかな多様体の上に完全に乗ったデータになります。
ノイズを乗せた場合には多様体からちょっとはみ出してしまいます。

なぜノイズを乗せるかというと、、、後で説明します。

**Comment by ae14watanabe** [comment]
@kz-halfmoon 
あ，これ答えてないやん笑
要するにデータに対して仮定してる生成過程をトレースしてるわけね．
真の多様体からノイズが乗ってデータが生成されるでしょうという．
