### ISSUE TITLE
UKRの写像Yをメンバ変数にして外部から参照できるようにしたい

### ISSUE THREAD

**Issue by tsuno0829** [furukawa-laboratory/somf#159]
**target code 対象となるコード** 明確に分かっているならば書く
unsupervised_kernel_regression.py

**Is your feature request related to a problem? Please describe. この機能追加リクエストは何かの問題に関連していますか？**
何が問題かを明快かつ簡潔に説明する．例えば，〜なときにイライラする…など
@tsuno0829 が研究している階層型UKRで写像Yをメンバ変数で参照したい．

**Describe the solution you'd like 望む解決策の説明**
Yをメンバ変数に変える

**Describe alternatives you've considered 代替案の説明**
別の解決策があるならそれを書く
メンバ変数以外でYが外部から取得できるのであれば教えてほしいです

**Additional context 追加の説明**
スクリーンショットなどが必要であればどうぞ

**Comment by tsuno0829** [comment]
@ae14watanabe 
今のUKRだと観測データXに対する推定写像Yを取得する方法がないと思っているのですがいかがでしょうか？

**Comment by ae14watanabe** [comment]
学習済みのやつであれば，インスタンスukrを使って
```python3
Y = ukr.inverse_transform(Znew=ukr.Z)
```
でいけませんかね
（inverse_transformの動作確認した記憶があんまりないのでちゃんとコードは見て欲しいですが）

**Comment by tsuno0829** [comment]
@ae14watanabe 
コード見た感じいけそうな気がするので試してみます！

**Comment by ae14watanabe** [comment]
1 epochごとにYが欲しいとかならまた別だろうけど，そういうことでは無いですもんねー

**Comment by tsuno0829** [comment]
> 1 epochごとにYが欲しいとかならまた別だろうけど，そういうことでは無いですもんねー

今UKR版のSOM2を考えているので1epochごとにYがほしい状況です

**Comment by tsuno0829** [comment]
slackの方で解決しましたのでこちらのissueは閉じます
