### ISSUE TITLE
I want SOM2

### ISSUE THREAD

**Issue by ae14watanabe** [furukawa-laboratory/somf#33]
**target code 対象となるコード**
libs/modelsにsom2クラスが欲しいです！

**Comment by ae14watanabe** [comment]
@tsuno0829 #59 と合わせて、こちらお願いできませんか？めっちゃ急ぎというわけでもないです。

**Comment by tsuno0829** [comment]
@ae14watanabe 
了解しました！変更内容はざっくりと分かったのでやってみます！
