### ISSUE TITLE
TSOMをTensorFlowで実装

### ISSUE THREAD

**Issue by hajime9652** [furukawa-laboratory/somf#50]
**target code 対象となるコード** 明確に分かっているならば書く
新しいモジュールの追加

**Is your feature request related to a problem? Please describe. この機能追加リクエストは何かの問題に関連していますか？**
SOMのTensorFlowモジュール

**Describe the solution you'd like 望む解決策の説明**
モジュール実装はしました。
チュートリアル作成中
TensorBoardの活用
・計算グラフの可視化
・モデルの可視化

**Comment by ae14watanabe** [comment]
#32 で解決
