### ISSUE TITLE
[bug] beverageで返す3次元配列のreshape方法について見直し

### ISSUE THREAD

**Issue by ae14watanabe** [furukawa-laboratory/somf#92]
**target library 対象となるライブラリ（コード）** どのコードでバグが起こっているのか明確ならばそれを書く
https://github.com/furukawa-laboratory/somf/blob/master/libs/datasets/real/beverage.py

**Describe the bug バグの説明**
元ファイルを読み込んだ直後の`temp_data` (shape=8456x11)とそれを`reshape(604,14,11)` した`x`が、こちらが想定している（人x飲料xシチュエーション）のテンソルになっていない可能性がある。
意図した通りにreshapeできていれば、以下が`allclose=True` になるはず
![image](https://user-images.githubusercontent.com/19607449/62021179-f2841f80-b200-11e9-9d40-8430056ccb4c.png)

おそらくreshapeでぐちゃぐちゃになっているため、TSOM2のCCPの結果もおかしい
![image](https://user-images.githubusercontent.com/19607449/62021113-acc75700-b200-11e9-97f5-37a95ed358b4.png)

**Expected behavior 期待される振る舞い**
上が`True`になること、また、`x[:,1,:]`等を実行しても矛盾がないこと。

**Comment by ae14watanabe** [comment]
以下のようにすれば良さそう
- temp_dataをsplitして604x11の配列14個作る
- それらを604x1x11にreshape
- concatenate(axis=1)

**Comment by takuro-Ishida** [comment]
岩崎さんが解決策を提案していただけました.
https://f-lab.slack.com/archives/C04E8B96F/p1564376268003500?thread_ts=1564374547.002800&cid=C04E8B96F

念の為、
`mixiDrinkData_Filter123.txt`をimportした配列と

`mixiDrinkData2_Filter123.txt`をimportして以下のように変換した配列
-    x = temp_data.reshape((604, 14, 11))
+    x = temp_data.reshape((14, 604, 11)).transpose(1,0,2)

がallcloseして一致することを確認するのがいいかなと思いました

**Comment by ae14watanabe** [comment]
@takuro-Ishida ラジャです、やります

**Comment by ae14watanabe** [comment]
@kpasso1015 以下の作業をお願いしたいです。
- branch #92 をフェッチ
- jupyterを別途作成し、その中で石田が言っている処理を行う
- 一致したxをipynb内で.npyとして吐き出す
- beverage.py内ではその.npyを読み込むように変更

終了したら、reviewを @ae14watanabe と あと一人誰か（石田は今日は忙しいので石田以外）に依頼してください
