### ISSUE TITLE
<som.py>コンストラクタで勝者ノード番号の初期値を外部から参照できるようにする

### ISSUE THREAD

**Issue by kpasso1015** [furukawa-laboratory/somf#97]
**target code 対象となるコード**
libs/models/som.py 

**Is your feature request related to a problem? Please describe. この機能追加リクエストは何かの問題に関連していますか？**
somを実装してsomfのsomとペアプロする際に
実行ファイルで用意した値で勝者ノード番号の初期化をおこなうようにしたい.

**Describe the solution you'd like 望む解決策の説明**

self.Z の条件分の中に処理を追加

**Comment by kpasso1015** [comment]
@takanoshuhei @forusufia 
今日PRで話してたやーつです

**Comment by takanoshuhei** [comment]
ありがとうございます　おかげでペアプロできました！！？
