### ISSUE TITLE
環境を共通化できるような仕組みの整備

### ISSUE THREAD

**Issue by ae14watanabe** [furukawa-laboratory/somf#99]
**target code 対象となるコード** 明確に分かっているならば書く

**Is your feature request related to a problem? Please describe. この機能追加リクエストは何かの問題に関連していますか？**
現在、各ライブラリのバージョンが明示されていないため、いざ実行させようとしても動作しない場合がある

例：https://github.com/furukawa-laboratory/somf/pull/69#issuecomment-546681343
**Describe the solution you'd like 望む解決策の説明**
何らかの環境を統一する仕組みが欲しい
poetry? venv?

**Comment by kpasso1015** [comment]
直接関係してないんですけど、
Theanoでみんな困っているんで何かしらに置き換えるようにしていきたいです....

**Comment by ae14watanabe** [comment]
あ、ごめんそれは別でIssue上げるつもりだったので上げます。PyTorchかtensorflowで置き換えるべきですね。

**Comment by ae14watanabe** [comment]
書きました。もうTheanoは使うべきじゃないよね。
いまいち何で使ってるのかまだ追いきれてないんだけど。
https://github.com/furukawa-laboratory/somf/issues/100

**Comment by ae14watanabe** [comment]
theanoとかtensorflowで作成したものはtestディレクトリに移行すべきですねー

**Comment by ae14watanabe** [comment]
あとこの辺はpoetry使うと行けそうですね、他にもやり方はあるだろうけど、PyPIにパッケージとして上げることとか考えるとpoetry管理が良さそう
